package person.backend.repositories;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import person.utility.HashUtil;

import java.io.IOException;
import java.sql.*;
import java.util.Map;


public class SessionRepo {
    private static Connection connection;
    private static Logger logger = LogManager.getLogger();

    public SessionRepo(Connection conn){
        this.connection = conn;
    }


    public int authenticate(Map<String,String> user) throws IOException {
        //for now just authenticate ragnar and flapjack
            PreparedStatement st = null;
            ResultSet rs = null;
            int success = 0;
            try {
                logger.info("Trying to authenticate username & password: " + user.get("username") + " " + user.get("password"));
                st = connection.prepareStatement("SELECT `id` FROM `User` WHERE `username` =? AND `password` =?");
                st.setString(1, user.get("username"));
                st.setString(2, user.get("password"));
                rs = st.executeQuery();
                rs.first();
                logger.info("checked user db, returned " + rs);
                success = rs.getInt(1);
                st.close();
                return success;

            } catch (SQLException throwables) {
                logger.error("Could not find username & password");
                throwables.printStackTrace();
                try {
                    st.close();
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
        return 0;
    }

    //Create session token with username and timestamp generated by db
    public static String createSessionToken(String text, int id){
        PreparedStatement st = null;
        ResultSet timeStamp = null;
        Timestamp time = null;
        String token = null;
        try{

            logger.info("username "+text);
            st = connection.prepareStatement("INSERT INTO `Session`(`username`,`id`) VALUES (?,?)");
            st.setString(1, text);
            st.setInt(2,id);
            st.executeUpdate();
            st = connection.prepareStatement("SELECT `time` FROM `Session` WHERE `username` =?");
            st.setString(1, text);
            st.executeQuery();
            timeStamp = st.getResultSet();
            timeStamp.first();
            time = timeStamp.getTimestamp("time");
            token = HashUtil.getCryptoHash(text + time.toString(), "SHA-256");
            logger.info("token is :" + token);

            st = connection.prepareStatement("UPDATE `Session` SET `token`=? WHERE `time` =?");
            st.setString(1, token);
            st.setTimestamp(2, time);
            st.executeUpdate();

        } catch (SQLException throwables) {
            throwables.printStackTrace();
        }finally {
            try {
                if(st != null)
                    st.close();
                    return token;
            } catch (SQLException e2) {
                e2.printStackTrace();
                return "error";
            }
        }

    }


}
